// src/components/async/index.tsx
import type { JSXOutput, Signal } from '@builder.io/qwik';
import { component$, useSignal, useTask$ } from '@builder.io/qwik';

type AsyncProps = {
  /** delay in milliseconds before rendering `isPending` component. @default 100 */
  delay?: number;
  /** signal to determine if component is pending. */
  isPending: Signal<boolean>;
  /** component to render while pending. */
  onPending: JSXOutput;
  /** component to render while delaying. @default <></> */
  onPreDelay?: JSXOutput;
  /** component to render when resolved. */
  onResolved: JSXOutput;
};

export const Async = component$<AsyncProps>(
  ({ isPending, delay = 100, onPreDelay: PreDelay = <></>, onPending: Pending, onResolved: Resolved }) => {
    const timeoutId = useSignal<number | undefined>();
    const isDelaying = useSignal(true);

    useTask$(({ track }) => {
      track(() => isPending.value);

      if (timeoutId.value !== undefined) {
        clearTimeout(timeoutId.value);
        timeoutId.value = undefined;
      }

      isDelaying.value = true;
      timeoutId.value = Number(
        setTimeout(() => {
          clearTimeout(timeoutId.value);
          timeoutId.value = undefined;
          isDelaying.value = false;
        }, delay),
      );
    });

    return isPending.value ? (isDelaying.value ? PreDelay : Pending) : Resolved;
  },
);

// src/lib/components/async/index.svelte
<script lang="ts">
  import type { Component } from 'svelte';

  type AsyncProps = {
    /** delay in milliseconds before rendering `isPending` component. @default 100 */
    delay?: number;
    /** signal to determine if component is pending. */
    isPending: boolean;
    /** component to render while pending. */
    onPending: Component;
    /** component to render while delaying. */
    onPreDelay?: Component;
    /** component to render when resolved. */
    onResolved: Component;
  };

  let { isPending = $bindable(), delay = 100, onPreDelay: PreDelay = () => ({}), onPending: Pending, onResolved: Resolved }: AsyncProps = $props();
  let isDelaying = $state(true);

  $effect(() => {
    if (isPending === false) {
      return;
    }

    isDelaying = true;

    const timeoutId = setTimeout(() => {
      isDelaying = false;
    }, delay);

    return () => {
      clearTimeout(timeoutId);
    };
  });
</script>

{#if isPending}
  {#if isDelaying}
    <PreDelay />
  {:else}
    <Pending />
  {/if}
{:else}
  <Resolved />
{/if}
